### ISSUE TITLE
Support of fp16 of LCM dreamshaper

### ISSUE THREAD

**Issue by Amin456789** [saddam213/OnnxStack#9]
Hi!

i just downloaded this fp16 model from here:
https://huggingface.co/aislamov/lcm-dreamshaper-v7-onnx/tree/main

it loads very fast and good but when i push on generate it stops immediately, i mean the model stays loaded but it wont generate anything, could u take a look at it @saddam213 @dakenf please? i am using cpu, so i don't know if its a gpu optimizd model or not

**Comment by jdluzen** [comment]
Looks like it doesn't like the unet's timestep. The fp16's is a float, the original is a long.

**Comment by jdluzen** [comment]
Yeah that was it: LatentConsistencyDiffuser.cs:198. I can't believe it's even faster now!

**Comment by saddam213** [comment]
That should be easy enough to support, let me see if I can squeeze it into tomorrows release

**Comment by jdluzen** [comment]
@saddam213 I've been trying to get a PR going, but I don't have access to the IOnnxModel in DiffuseAsync for GetInputMetadata.

**Comment by saddam213** [comment]
Sorry I missed your PR and already commited a fix

GetInputMetadata is accessible and worked perfect, out implementations were pretty much the same

Thanks for the PR

**Comment by saddam213** [comment]
Latest commit will fix the issue for both pipelines, added the functionality to both diffuser base classes but I think implementation should be moved to a shared place as new pipelines will also need this I would assume.

Perhaps we need a static helper class for methods like these, as DecodeLatents is the same across both as well

**Comment by Amin456789** [comment]
uh nice, thanks guys! cant wait for the update to test it out

**Comment by dakenf** [comment]
Hello everyone! If you don't mind, i'll give you some tips on model conversion based on this [doc]( https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/README.md)

Long story short, if you run fusion optimizer on the model, it will combine many ops into one. So from 3k+ ops it will get to 1k+. That will lead to VRAM/RAM decrease (less GPU buffers allocated for each node input/output) and performance optimizations, since CUDA and DML have fused attention kernels

I've been using this script, it already has optimized settings for DML https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16/blob/main/conv_sd_to_onnx.py but with some changes.
<img width="783" alt="image" src="https://github.com/saddam213/OnnxStack/assets/7466130/4c0c11f8-6b90-4cfb-b1a1-8cab22cc91b4">
Last 4 lines (disable BiasAdd, BiasSplitGelu, packed KV and QKV) are required if you want the model to work on CPU. Bias* kernels are not implemented for CPU in ONNX and packed KV/QKV for MultiHeadAttention are not supported on CPU too

With these optimizations and fp16 you should be able to run unet with less than 5gb VRAM. You can check results with this model i've converted for WebGPU https://huggingface.co/aislamov/stable-diffusion-2-1-base-onnx/tree/main

Feel free to ask me any questions if you have!

**Comment by Amin456789** [comment]
> Hello everyone! If you don't mind, i'll give you some tips on model conversion based on this [doc](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/README.md)
> 
> Long story short, if you run fusion optimizer on the model, it will combine many ops into one. So from 3k+ ops it will get to 1k+. That will lead to VRAM/RAM decrease (less GPU buffers allocated for each node input/output) and performance optimizations, since CUDA and DML have fused attention kernels
> 
> I've been using this script, it already has optimized settings for DML https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16/blob/main/conv_sd_to_onnx.py but with some changes. <img alt="image" width="783" src="https://user-images.githubusercontent.com/7466130/281654236-4c0c11f8-6b90-4cfb-b1a1-8cab22cc91b4.png"> Last 4 lines (disable BiasAdd, BiasSplitGelu, packed KV and QKV) are required if you want the model to work on CPU. Bias* kernels are not implemented for CPU in ONNX and packed KV/QKV for MultiHeadAttention are not supported on CPU too
> 
> With these optimizations and fp16 you should be able to run unet with less than 5gb VRAM. You can check results with this model i've converted for WebGPU https://huggingface.co/aislamov/stable-diffusion-2-1-base-onnx/tree/main
> 
> Feel free to ask me any questions if you have!

hi! thank u so much for sharing this, sadly i have no idea how to code to do it myself, could u please make some fp16 models for cpu too? lyriel v16, deliberate v2 or v3, epiCRealism are a few good ones, i would like to use and test them out in onnxstack if possible, thanks

**Comment by Amin456789** [comment]
LCM fp16 now works very good and it is so fast! but i have no idea what is going on as i used 0 device for unet and the rest on 1 so i think it uses my AMD and Intel gpus [in task manager my intel graphic goes 99% usage so it is mostly this gpu] not the cpu this time, 

i close it this topic if it is ok now
